# Generated by Django 4.2.6 on 2023-10-20 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("college", models.CharField(max_length=250)),
                ("degree", models.CharField(max_length=200)),
                ("certification", models.TextField()),
                ("date_start", models.DateField()),
                ("date_end", models.DateField()),
            ],
        ),
    ]
