# Generated by Django 4.2.6 on 2023-10-20 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(max_length=50)),
                ("company", models.CharField(max_length=50)),
                ("testimonial", models.TextField()),
                ("date", models.DateField()),
            ],
        ),
    ]
